// lib/models/nfl.dart

enum NflTeam {
  bills,
  dolphins,
  patriots,
  jets,
  ravens,
  bengals,
  browns,
  steelers,
  texans,
  colts,
  jaguars,
  titans,
  broncos,
  chiefs,
  raiders,
  chargers,
  cowboys,
  giants,
  eagles,
  commanders,
  bears,
  lions,
  packers,
  vikings,
  falcons,
  panthers,
  saints,
  buccaneers,
  cardinals,
  rams,
  sf49ers, // ✅ consistent with nfl_brands.dart
  seahawks,
}

const Map<NflTeam, String> nflTeamName = {
  NflTeam.bills: "Buffalo Bills",
  NflTeam.dolphins: "Miami Dolphins",
  NflTeam.patriots: "New England Patriots",
  NflTeam.jets: "New York Jets",
  NflTeam.ravens: "Baltimore Ravens",
  NflTeam.bengals: "Cincinnati Bengals",
  NflTeam.browns: "Cleveland Browns",
  NflTeam.steelers: "Pittsburgh Steelers",
  NflTeam.texans: "Houston Texans",
  NflTeam.colts: "Indianapolis Colts",
  NflTeam.jaguars: "Jacksonville Jaguars",
  NflTeam.titans: "Tennessee Titans",
  NflTeam.broncos: "Denver Broncos",
  NflTeam.chiefs: "Kansas City Chiefs",
  NflTeam.raiders: "Las Vegas Raiders",
  NflTeam.chargers: "Los Angeles Chargers",
  NflTeam.cowboys: "Dallas Cowboys",
  NflTeam.giants: "New York Giants",
  NflTeam.eagles: "Philadelphia Eagles",
  NflTeam.commanders: "Washington Commanders",
  NflTeam.bears: "Chicago Bears",
  NflTeam.lions: "Detroit Lions",
  NflTeam.packers: "Green Bay Packers",
  NflTeam.vikings: "Minnesota Vikings",
  NflTeam.falcons: "Atlanta Falcons",
  NflTeam.panthers: "Carolina Panthers",
  NflTeam.saints: "New Orleans Saints",
  NflTeam.buccaneers: "Tampa Bay Buccaneers",
  NflTeam.cardinals: "Arizona Cardinals",
  NflTeam.rams: "Los Angeles Rams",
  NflTeam.sf49ers: "San Francisco 49ers", // ✅ fixed
  NflTeam.seahawks: "Seattle Seahawks",
};
